version: "3"
services:
  debian:
    build:
      context: debian
    image: devel:debian
  ubuntu:
    build:
      context: ubuntu
    image: devel:ubuntu
  centos:
    build:
      context: centos
    image: devel:centos
  fedora:
    build:
      context: fedora
    image: devel:fedora
