---
version: "3"
services:
  debug:
    restart: always
    image: mitsutaka/devel:arch
    container_name: devel
    hostname: devel
    network_mode: bridge
    volumes:
      - /home/mitz:/home/mitz
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
    tmpfs:
      - /run
      - /var/lib/journal
    stop_signal: RTMIN+3  # systemd
    tty: true             # show "boot" log
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_BROADCAST
      - NET_RAW
      - SYS_ADMIN
      - SYS_PTRACE
      - SYS_RESOURCE
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
